### ISSUE TITLE
File missing & DSP editor

### ISSUE THREAD

**Issue by seek78** [uniface/Web#2] opened 2017-01-04 07:41 UTC
Hello,
launching the IDF after the project setup, the **ADDITIONAL** menu doesn't appear.
The problem seem the be the missing of files:
- src\library\menu\USYS\USA\FILESYNC.mnx
- src\library\menu\USYS\USA\FILESYNC_Menu.xml

Replacing the .men with the one of uniface-localweb project solve the problem, but it's impossible to open the DSP's editor.

Thanks for your work
Seek
---EDIT---
The problem is referred to project **uniface-basic-web-framework**

**Comment by uf-dakerman** [comment] 2017-01-04 13:51
Hi, I've encountered this issue before. The broken menu is caused by the additional menu referencing the filesync menu, which was either omitted from the distribution or not imported. I plan to do some work on that and commit some changes to alleviate the problem and some other issues. Are you using Uniface 9.6 or 9.7 (as I may only provide the updates for 9.7)? 

In the mean time, you can do the following:

a) Import the menus from the development tooling uniface-version-control project:
https://github.com/uniface/Development-Tooling/tree/master/uniface-version-control/src/library/menu/USYS/USA 

do this via the command line (the dialog box that pops up when starting the IDE if you have a ? at the end of the shortcut target), e.g. /imp C:\temp\filesync.mnx. If you don't have an addition menu, you can also import that, otherwise you may want to add a reference to the new filesync menu.

b) Recompile the menus, e.g. /men from the dialog box

Try restarting the IDE - hopefully the menu will be fixed now.

Kind Regards,
David

**Comment by seek78** [comment] 2017-01-04 14:02
Hi David,
I've already solved the problem as mentioned, I'm using 9.7.
Now I'm facing with another problem on this project: the edit button does not work for users.

Kind Regards,
Seek

**Comment by thomassshore** [comment] 2017-01-04 19:34
Seek,
Both the menu and id selection are fixed in the latest updates.
Tom

**Closed as completed by thomassshore** 2017-01-04 19:34 UTC

**Comment by seek78** [comment] 2017-01-05 07:50
Thanks all!
Seek

**Comment by seek78** [comment] 2017-01-05 08:46
Sorry Tom,
victory declared too soon...
```
Compile Menu: 'ADDITIONAL'
     error: 1126 - Cannot compile; specified information not found.
Menu compiler messages: [info 0, warnings 0, errors 1] in 1 menu(s)

```

Regards
S.
